steps:
  # Install Node.js dependencies and build React app
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: 'client'
    
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'client'
    env:
      - 'REACT_APP_API_URL=https://hackathon-genai-475313.uc.r.appspot.com'
      - 'CI=false'
  
  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'app'
      - 'deploy'
      - '--quiet'

timeout: '1600s'
